services:
  - name: eagleeye-backend
    type: web
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
  - name: eagleeye-frontend
    type: web
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port 80 --server.address 0.0.0.0"
