services:
  - name: eagleeye-backend
    type: web
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
  - name: eagleeye-frontend
    type: web
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"
